sylius_resource:
  resources:
    guiziweb_gemini.prompt:
      classes:
        model: Guiziweb\GeminiSeoPlugin\Entity\Prompt
        repository: Guiziweb\GeminiSeoPlugin\Repository\PromptRepository
        form: Guiziweb\GeminiSeoPlugin\Form\Type\PromptType

sylius_grid:
  grids:
    guiziweb_gemini_prompt:
      driver:
        name: doctrine/orm
        options:
          class: Guiziweb\GeminiSeoPlugin\Entity\Prompt
      fields:
        id:
          type: string
          label: 'ID'
          sortable: true
        code:
          type: string
          label: 'Code'
        text:
          type: string
          label: 'Text'

        structure:
          type: string
          label: 'Structure'
      actions:
        item:
          update:
            type: update
      filters:
        text:
          type: string
          label: 'Text'