services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Guiziweb\GeminiSeoPlugin\Service\Prompt:
        autowire: true

    Guiziweb\GeminiSeoPlugin\Repository\PromptRepository:
        autowire: true

    Guiziweb\GeminiSeoPlugin\Controller\GeminiController:
        autowire: true
        tags: ['controller.service_arguments']

    Guiziweb\GeminiSeoPlugin\Form\Extension\ProductTranslationTypeExtension:
        arguments:
            - '@router'
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\ProductBundle\Form\Type\ProductTranslationType }

    Guiziweb\GeminiSeoPlugin\EventListener\AdminMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addCustomMenuItem }
